Add deu, fra, ita, eng labels to admin2
whosonfirst-data/whosonfirst-data-admin-ch pull request #23
Opened 2021-02-01 23:13 UTC by stepps00

Fixes a portion of https://github.com/whosonfirst-data/whosonfirst-data/issues/1640

This PR adds German, French, English, and Italian `label` properties to admin2 in Switzerland. In a handful of cases (large cities), the longname label does not include the placetype, as the placetype is not used when referring to that place. So, in a handful of cases, the original English longname values were overwritten and not stored as variants.

I've hand-curated some of these tougher-to-find label strings, but the majority were pulled from [this doc](http://webcache.googleusercontent.com/search?q=cache:T3_UWxaK0AUJ:www.nla.gov.au/lis/stndrds/grps/acoc/documents/EPC133-9.1.doc+&cd=1&hl=en&ct=clnk&gl=us) (cached doc), then verified through Wikipedia or Wikidata.

No PIP work required, can merge once approved.

2021-02-01 23:58 UTC, nvkelso commented on data/102/062/775/102062775.geojson
> +        "district"
Should this be `bezirk` instead of `district` to match the longname value?

2021-02-01 23:58 UTC, nvkelso commented on data/102/062/779/102062779.geojson
> +        "district"
Similar comment to above.

2021-02-01 23:58 UTC, nvkelso commented on data/102/062/791/102062791.geojson
> +        "district"
Quite a few of these miss-matches.

2021-02-02 00:00 UTC, nvkelso requested changes
This generally looks good. But the French labels should be consistent between 

```
"label:fra_x_preferred_longname":[
        "Bezirk Blenio"
    ],
    "label:fra_x_preferred_placetype":[
        "district"
    ],
```

So they should both say Bezirk or both say District.

2021-02-02 00:20 UTC, stepps00 commented
Looks like the first commit mixed up the `fra` label properties, but those were fixed in 41a1ff7. Generally, the properties and values should look like this example, where the palce name is "Riviera":

```
    "label:deu_x_preferred_longname":[
        "Bezirk Riviera"
    ],
    "label:deu_x_preferred_placetype":[
        "bezirk"
    ],
    "label:eng_x_preferred_longname":[
        "Riviera District"
    ],
    "label:eng_x_preferred_placetype":[
        "district"
    ],
    "label:fra_x_preferred_longname":[
        "District de Riviera"
    ],
    "label:fra_x_preferred_placetype":[
        "district"
    ],
    "label:ita_x_preferred_longname":[
        "Distretto di Riviera"
    ],
    "label:ita_x_preferred_placetype":[
        "distretto"
    ],
```

German: "bezirk"
English and French: "district"
Italian: "distretto"

2021-02-02 17:34 UTC, nvkelso approved these changes
LGTM

2021-02-02 19:35 UTC, merged